#!/bin/bash

icon=""
cap_percentage=$(df -h --output=pcent / | awk 'NR%2==0 {print $0}'  | cut -f 1 -d '%'  | xargs)
if   [[ "$cap_percentage" -ge 90 ]]; then
    printf "$icon $cap_percentage\n"
elif [[ "$cap_percentage" -ge 80 ]] && [[ "$cap_percentage" -ge 89 ]]; then
    printf "$icon $cap_percentage\n"
else
    printf "$icon $cap_percentage\n"
fi
